# Generated by Django 5.1 on 2024-08-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'attendance_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'staff_master',
                'managed': False,
            },
        ),
    ]
